version: "3.9"
services:
  php-apache:
    ports:
      - "9000:80"
    build: './build/php'
    volumes:
      - ./ex1:/var/www/html/ex1
      - ./ex2:/var/www/html/ex2
      - ./ex3:/var/www/html/ex3
  db:
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATBASE: my-website
    volumes:
      - dbData:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80
volumes:
  app:
  dbData:
